<!-- FEATURED HERE -->
<article>
    <div class="row">
        <div class="span9">
            <h3><?= _('Lista de Categorías');?></h3>
        </div>
        <div class="span3">
            <?= Html::linkAction('agregar', _('Agregar'), 'class="btn btn-success"'); ?>
        </div>
    </div>
    <div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th><?= _('Nombre');?></th>
                <th><?= _('Opciones');?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($categorias->items as $categoria): ?>
            <tr>
                <td><?= $categoria->id; ?></td>
                <td><?= $categoria->nombre; ?></td>
                <td>
                    <?= Html::linkAction('editar/' . $categoria-id, _('Editar')); ?> 
                    <?= Html::linkAction('eliminar/' . $categoria-id, _('Eliminar')); ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>

</article>