<!-- FEATURED HERE -->
<article>
    <div class="row">
        <div class="span9">
            <h3>Webs Creadas con KumbiaPHP Framework</h3>
        </div>
        <div class="span3">
            <?= Html::linkAction('agregar', 'Agregar', 'class="btn btn-success"'); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8 text-center">
            <div class="image-box box-grey">
                <span class="btn btn-default btn-block">Web destacada</span>
                <?= Html::img('web/website-' . $featured->id . ".png", ""); ?>
            </div>
        </div>
        <div class="span4">
            <div class="image-box box-grey">
                <h3 class="box-header"><a href="#"><?= $featured->url; ?></a></h3>
                <div class="row">
                    <div class="span9">
                        <strong>Autor:</strong> <?= $featured->getAutor()->nombre; ?>
                        <br/>
                        <strong>País:</strong> <?= $featured->getAutor()->pais; ?>
                    </div>
                    <div class="span3">
                        <?= Html::gravatar($featured->getAutor()->email, "", "class='box'"); ?>
                    </div>
                </div>
                <?php if (count($featured->getAutor()->getAutorSocial()) > 0) { ?>
                    <div class="row">
                        <h4 class="box-header">Contacto</h4>
                        <table>
                            <?php foreach ($featured->getAutor()->getAutorSocial() as $item): ?>
                                <tr>
                                    <td>
                                        <a class="social <?= strtolower($item->socialname); ?>" href="#"></a>
                                    </td>
                                    <td>
                                        <?= $item->cuenta; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</article>
<!-- OTHERS -->

<div class="row">
    <?php foreach ($listado->items as $l) { ?>
        <div class="span3 text-center">
            <div class="thumb">
                <?php
                    if ($l->grafico) {
                        echo Html::img("web/upload/thumb/$l->grafico", 'img-web', 'width="100%"');
                    } else {
                        echo Html::img("web/upload/thumb/no.jpg", 'img-web');
                    }
                ?>
            </div>
            <br/>
            <div class="center">
                <a href="http://<?= $l->url ?>" target="_blank" class="btn-block"><?= $l->url ?></a>
                <small>Desarrollador por: <strong><?= (new Autor())->dame_autor($l->autor_id) ?></strong></small>
            </div>
            <br/>
        </div>
    <?php } ?>
</div>

<div class="row">
<div class="span12"><?= View::partial('paginators/punbb', false, array('page' => $listado, 'show' => 10, 'url' => "usuarios/index"))?></div>
</div>
