<!DOCTYPE html>
<html lang="es" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="utf-8">
        <title>KumbiaPHP web y app PHP Framework en español - KumbiaPHP</title>
        <!--[if lt IE 9]> <script type="text/javascript" src="<?= PUBLIC_PATH ?>javascript/html5shiv"</script> <![endif]-->
        <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/structure2.css">
        <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/vanilla-modal.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:type" content="website">
        <meta property="og:image" content="http://proto.kumbiaphp.com/img/logo250.png">
        <script type="text/javascript" src="<?= PUBLIC_PATH ?>javascript/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?= PUBLIC_PATH ?>javascript/app.js"></script>
    </head>
    <body>
        <nav>
            <div class="row">
                <a href="/" class="span3 logo" title="KumbiaPHP Framework PHP MVC" >
                <img src="<?= PUBLIC_PATH ?>img/kumbiaphp.png" alt="KumbiaPHP Framework" width="259" height="30" /></a>
                <div class="span9">
                    <ul class="menu index">
                        <li><a href="<?= PUBLIC_PATH ?>caracteristicas/" class="caracteristicas" >Características</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>escaparate/" class="escaparate" >Escaparate</a></li>
                        <li><a href="//www.kumbiaphp.com/blog/">Blog</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>aprender/" class="aprender" >Documentación</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>comunidad/" class="comunidad" >Comunidad</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>descargas/" class="descargas" >Descargar</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="content">
            <?php View::content() ?>


            <footer>
                <div class="row">
                    <div class="span6">
                        <p>Web creada con KumbiaPHP</p>
                    </div>
                    <div id="social" class="span6">
                        <p>¡Compártelo!</p>
                        <a class="social facebook" rel="nofollow" href="https://www.facebook.com/share.php?u=http://proto.kumbiaphp.com/&t=KumbiaPHP+web+y+app+PHP+Framework+en+espa%C3%B1ol+-+KumbiaPHP" title="Facebook" target="_blank"></a>
                        <a class="social twitter" rel="nofollow" href="https://twitter.com/intent/tweet?text=KumbiaPHP+web+y+app+PHP+Framework+en+espa%C3%B1ol+-+KumbiaPHP&url=http://proto.kumbiaphp.com/&via=KumbiaPHP" title="Twitter" target="_blank"></a>
                        <a class="social google" rel="nofollow" href="https://plusone.google.com/_/+1/confirm?hl=es&url=http://proto.kumbiaphp.com/" title="Google +1" target="_blank"></a>
                    </div>
                </div>
            </footer>
            <script src="<?= PUBLIC_PATH; ?>javascript/vanilla-modal.js"></script>
        </div>
    </body>
</html>
